# Generated by Django 6.0.3 on 2026-04-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_admission_curriculumphase_phase_practicumproject_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EnrollmentFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("currency_inr", models.PositiveIntegerField(default=50000)),
                ("currency_usd", models.PositiveIntegerField(default=600)),
                (
                    "details",
                    models.TextField(
                        help_text="Comma-separated features, e.g. 1-on-1 GenAI Expert Mentorship, 8 Graded Production Assignments"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Faculty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "initials",
                    models.CharField(help_text="Short initials, e.g. PR", max_length=4),
                ),
                ("title", models.CharField(max_length=100)),
                ("bio", models.TextField()),
                ("linkedin", models.URLField(blank=True)),
                (
                    "skills",
                    models.CharField(
                        help_text="Comma-separated skills", max_length=300
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LogisticsSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
