# Generated by Django 6.0.3 on 2026-04-05 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_practicumvertical"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tutor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("title", models.CharField(blank=True, max_length=150)),
                ("bio", models.TextField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("staff", "Staff"),
                    ("student", "Student"),
                    ("user", "User"),
                ],
                default="user",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="tutor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="core.tutor",
            ),
        ),
    ]
