# Generated by Django 6.0.3 on 2026-04-05 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_tutor_user_active_alter_user_user_type_user_tutor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="tutor",
        ),
        migrations.AddField(
            model_name="user",
            name="faculty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to="core.faculty",
            ),
        ),
        migrations.DeleteModel(
            name="Tutor",
        ),
    ]
