# Generated by Django 6.0.3 on 2026-04-05 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_remove_user_tutor_user_faculty_delete_tutor"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Batch or cohort name, e.g. Fall 2026", max_length=200
                    ),
                ),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional capacity for the batch",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["start_date"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="current_role",
            field=models.CharField(
                blank=True,
                help_text="Current professional role or job title",
                max_length=150,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mobile_number",
            field=models.CharField(
                blank=True, help_text="Mobile number for the user", max_length=25
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="enrolled_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="core.coursebatch",
            ),
        ),
    ]
